[package]
name = "diceware"
version = "0.1.0"
authors = ["Simon Morgan <sjm@sjm.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.*"
rand = "0.7"